#!/usr/bin/env bash
# Bash Guard Hook
# Blocks destructive commands before they execute.
# Generated by Agent Project Creator (framework v2.1).
# Edit DANGEROUS_PATTERNS below to customise for your environment.

set -euo pipefail

input="$(cat)"

command="$(printf '%s' "$input" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('tool_input', {}).get('command', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")"

if [ -z "$command" ]; then
  exit 0
fi

DANGEROUS_PATTERNS=(
  'rm[[:space:]]+-[a-zA-Z]*r[a-zA-Z]*f?[a-zA-Z]*[[:space:]]+/'
  'rm[[:space:]]+-[a-zA-Z]*r[a-zA-Z]*f?[a-zA-Z]*[[:space:]]+\*'
  'rm[[:space:]]+-[a-zA-Z]*r[a-zA-Z]*f?[a-zA-Z]*[[:space:]]+~'
  '\bgit[[:space:]]+push[[:space:]]+.*--force'
  '\bgit[[:space:]]+push[[:space:]]+.*[[:space:]]-f($|[[:space:]])'
  '\bgit[[:space:]]+reset[[:space:]]+--hard'
  '\bgit[[:space:]]+clean[[:space:]]+-[a-zA-Z]*f[a-zA-Z]*d'
  '\bdd[[:space:]]+if='
  '\bmkfs\.'
  '>[[:space:]]*/dev/sd[a-z]'
  ':\(\)\{[[:space:]]*:\|:&[[:space:]]*\};:'
  '\bchmod[[:space:]]+-R[[:space:]]+777'
  '\bsudo[[:space:]]+rm\b'
)

for pattern in "${DANGEROUS_PATTERNS[@]}"; do
  if printf '%s' "$command" | grep -Eq "$pattern"; then
    echo "BLOCKED by bash-guard.sh: command matches destructive pattern: $pattern" >&2
    echo "Command was: $command" >&2
    echo "If this is intentional, surface it to the user in chat and ask for explicit confirmation. Do not retry the same command silently." >&2
    exit 2
  fi
done

exit 0
